const config = {
  NOTION_PAGE_ID: '8bce7b6d65558324a630012e3e45769b',
  THEME: 'hexo',
  LANG: 'zh-CN',
  SINCE: 2026,
  PSEUDO_STATIC: false,
  NEXT_REVALIDATE_SECOND: 60,
  REVALIDATION_TOKEN: '',
  APPEARANCE: 'light',
  APPEARANCE_DARK_TIME: [18, 6],
  AUTHOR: '视频工具站',
  BIO: 'AE插件 · 视频教程 · 实用工具 · LOL绝活',
  LINK: 'https://notion-next-w9u4.vercel.app',
  KEYWORDS: 'AE插件,PR预设,视频教程,实用工具,LOL,绝活',
  BLOG_FAVICON: '/favicon.ico',
  BEI_AN: '',
  BEI_AN_LINK: 'https://beian.miit.gov.cn/',
  BEI_AN_GONGAN: '',
  ENABLE_RSS: true,
  ...require('./conf/comment.config'),
  ...require('./conf/contact.config'),
  ...require('./conf/post.config'),
  ...require('./conf/analytics.config'),
  ...require('./conf/image.config'),
  ...require('./conf/font.config'),
  ...require('./conf/right-click-menu'),
  ...require('./conf/code.config'),
  ...require('./conf/animation.config'),
  ...require('./conf/widget.config'),
  ...require('./conf/ad.config'),
  ...require('./conf/plugin.config'),
  ...require('./conf/ai.config'),
  ...require('./conf/performance.config'),
  ...require('./conf/top-tag.config'),
  ...require('./conf/layout-map.config'),
  ...require('./conf/notion.config'),
  ...require('./conf/dev.config'),
  CUSTOM_EXTERNAL_JS: [''],
  CUSTOM_EXTERNAL_CSS: [''],
  CUSTOM_MENU: true,
  CAN_COPY: true,
  ...require('./conf/techgrow.config'),
  LAYOUT_SIDEBAR_REVERSE: false,
  GREETING_WORDS: 'AE插件, 视频教程, 实用工具, LOL绝活, 欢迎来到我的网站',
  UUID_REDIRECT: false
};
module.exports = config;
